---
- name: Check if time is synchronized (ntp test)
  command: "timedatectl status"
  register: time_synchronization
  changed_when: false
  tags:
    - skip_ansible_lint

# ulimit needs full shell
- name: Register number of file descriptors
  shell: "ulimit -n"
  register: file_descriptors
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Fail on desynchronized time
  fail:
    msg: "Synchronize time with NTP. Follow instructions at https://docs.fluentd.org/v1.0/articles/before-install"
  when: not time_synchronization.stdout_lines[5].split(":")[1].strip()|bool

- name: Fail on too small number of file descriptors
  fail:
    msg: "Increase number of file descriptors to more than 1024. Follow instructions at https://docs.fluentd.org/v1.0/articles/before-install"
  when: file_descriptors.stdout < "1025"

- name: Fail on source not having type
  fail:
    msg: "Each of your input plugin should have its type defined"
  when: item.type is not defined
  loop: "{{ fluentd_sources_conf }}"

- name: Fail on output not having type
  fail:
    msg: "Each of your output plugin should have its type defined"
  when: item.type is not defined
  loop: "{{ fluentd_outputs_conf }}"

- name: Fail on output not having tag
  fail:
    msg: "Each of your output plugin should have its tag defined"
  when: item.tag is not defined
  loop: "{{ fluentd_outputs_conf }}"

- name: Fail on filter not having tag
  fail:
    msg: "Each of your filter plugin should have its tag defined"
  when: item.tag is not defined
  loop: "{{ fluentd_filters_conf }}"
